### ISSUE TITLE
Close issue comment should be ignored

### ISSUE THREAD

**Issue by pdhoolia** [pdhoolia/se-agent#8] opened 2024-11-07 17:24 UTC
Let's ignore issue comments that close the issue from our event processing.

**Comment by se-agent** [comment] 2024-11-07 17:24
To address the issue of ignoring comments that close an issue during event processing, we need to identify such comments and ensure they are not processed by the application. In GitHub, an issue can be closed automatically when a comment contains certain keywords like "fixes #issue_number", "resolves #issue_number", or when a pull request that references the issue is merged. 

Here's how we can implement this:

### Steps and Code Changes

1. **Modify the `process_issue_event` function in `listener_core.py`**:
   - Check if the comment body contains any keywords indicating that it closes an issue.

2. **Implement ignore logic**:
   - If the comment contains a closing keyword, return a status that indicates the comment is ignored.

Here is a code snippet illustrating these changes:

#### Code Update in `listener_core.py`

Locate the `process_issue_event` function and update it as follows:

```python
def process_issue_event(project: Project, issue_details, comment_details=None):
    """
    Processes new issues and issue comments.
    """
    # Check if the comment is made by the agent itself
    if comment_details:
        comment_body = comment_details.get('body', '')
        
        # Ignore comments that are from the agent itself
        if '<!-- SE Agent -->' in comment_body:
            print("Ignoring agent's own comment")
            return IGNORE_TOKEN
        
        # Ignore comments that close the issue
        closing_keywords = ["fixes", "resolves", "closes"]
        if any(keyword in comment_body.lower() for keyword in closing_keywords):
            print("Ignoring comment that closes the issue")
            return IGNORE_TOKEN

    # Analyze, localize, and suggest changes for the issue
    try:
        analysis_results = analyze_issue(project, issue_details)
        logger.debug(f"Analysis results: {analysis_results}")
        localization_results = localize_issue(project, issue_details, analysis_results)
        logger.debug(f"Localization results: {localization_results}")
        change_suggestions = suggest_changes(project, analysis_results, localization_results)
        logger.debug(f"Change suggestions: {change_suggestions}")
    except Exception as e:
        logger.exception("Error processing issue.")
        return None

    # Get the issue number
    issue_number = issue_details['number']

    # Post the change suggestions as a comment on the GitHub issue
    try:
        # Include the special marker to identify agent's own comments
        agent_comment = f"<!-- SE Agent -->\n{change_suggestions}"
        project.post_issue_comment(issue_number, agent_comment)
    except Exception as e:
        logger.exception("Error posting comment to GitHub.")
        return None

    return change_suggestions
```

### Explanation
- **Check for closing keywords**: We added logic to check if the comment contains any of the typical closing keywords like "fixes", "resolves", or "closes". If such a keyword is found, the comment is ignored for further processing by returning `IGNORE_TOKEN`.
- **Lowercase the comment body**: The comment body is converted to lowercase to ensure the keyword check is case-insensitive.

This change ensures that comments intended to close issues are not analyzed or processed by the system.

**Comment by pdhoolia** [comment] 2024-11-07 17:25
can you please point out the proposed changes in git diff format?

**Comment by se-agent** [comment] 2024-11-07 17:25
Certainly! Below are the proposed changes in `git diff` format for the `listener_core.py` file:

```diff
def process_issue_event(project: Project, issue_details, comment_details=None):
    """
    Processes new issues and issue comments.
    """
    # Check if the comment is made by the agent itself
    if comment_details:
        comment_body = comment_details.get('body', '')

        # Ignore comments that are from the agent itself
        if '<!-- SE Agent -->' in comment_body:
            print("Ignoring agent's own comment")
            return IGNORE_TOKEN

+        # Ignore comments that close the issue
+        closing_keywords = ["fixes", "resolves", "closes"]
+        if any(keyword in comment_body.lower() for keyword in closing_keywords):
+            print("Ignoring comment that closes the issue")
+            return IGNORE_TOKEN

    # Analyze, localize, and suggest changes for the issue
    try:
        analysis_results = analyze_issue(project, issue_details)
        logger.debug(f"Analysis results: {analysis_results}")
        localization_results = localize_issue(project, issue_details, analysis_results)
```

### Explanation of Diff
- **Added Lines**: The `+` sign indicates new lines added to the function.
- **New Logic**:
  - A list `closing_keywords` contains typical GitHub keywords that can close issues.
  - We check if any of these keywords exist in the comment body, converted to lowercase for case-insensitive comparison.
  - If such a keyword is found, the function returns `IGNORE_TOKEN` to skip processing this comment.

**Closed** 2024-11-07 17:33 UTC
